swagger: '2.0'
info:
  title: video-stream-functions
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /getFilm:
    get:
      summary: Get Film list
      operationId: getFilm
      x-google-backend:
        address: https://europe-central2-video-streaming-390616.cloudfunctions.net/getFilmFunction
      responses:
        '200':
          description: Received a film list
          schema:
            type: string
  /postFilm:
    get:
      summary: Post a film object
      operationId: postFilm
      x-google-backend:
        address: https://europe-central2-video-streaming-390616.cloudfunctions.net/postFilmFunction
      responses:
        '301':
          description: Film was added to database
          schema:
            type: application/json