spring:
  datasource:
    username: root
    password: dA1k2F8kC45DuoO5C
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.49.3/video-streaming-functions-db
#    url: jdbc:mysql://34.118.47.249/video-streaming-functions-db
  jpa:
    hibernate:
      ddl-auto: update
    default:
      properties:
        hibernate:
          bytecode:
            provider: none
  cloud:
#      definition: getFilm;postFilm;getFilmList
    gcp:
      sql:
        instance-connection-name: video-stream-instance:europe-central2:video-streaming-functions-db
        database-name: video-streaming-functions-db
      config:
        credentials:
          location: video-streaming-faas.json

